name: Bandit

on: [push, pull_request]

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-pipenv
          restore-keys: |
            ${{ runner.os }}-pip-pipenv

      - name: Cache pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Setup pipenv
        run: python -m pip install --upgrade pipenv

      - name: Install dependencies using pipenv
        run: |
           cd $GITHUB_WORKSPACE
           python -m pipenv install --dev

      - name: Run Bandit
        run: |
          cd $GITHUB_WORKSPACE
          pipenv run bandit -r buildnis -f xml -o bandit_out.xml

      - name: Publish Bandit Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: bandit_out.xml
