name: Ubuntu 20.04

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-pipenv
          restore-keys: |
            ${{ runner.os }}-pip-pipenv

      - name: Cache pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install Doxygen
        run: |
          sudo apt install doxygen

      - name: Setup pipenv
        run: python -m pip install --upgrade pipenv

      - name: Install dependencies using pipenv
        run: |
           cd $GITHUB_WORKSPACE
           python -m pipenv install --dev

      - name: Run Buildnis
        run: |
          cd $GITHUB_WORKSPACE
          pipenv run python -m buildnis ./test_project/project_config.json -v --log-file log_file.txt --gen conf_out

      - uses: actions/upload-artifact@v2
        with:
          name: Buildnis Debug Log
          path: log_file.txt

      - uses: actions/upload-artifact@v2
        with:
          name: Buildnis JSON Configs
          path: test_project/conf_out/*.json

      - name: Clean Buildnis
        run: |
          cd $GITHUB_WORKSPACE
          pipenv run python -m buildnis ./test_project/project_config.json -vv --clean

      # - name: Re-Run Buildnis
      #   run: |
      #     cd $GITHUB_WORKSPACE && pipenv run python -m buildnis ./test_project/project_config.json -vv

      - name: Dist-Clean Buildnis
        run: |
          cd $GITHUB_WORKSPACE
          pipenv run python -m buildnis ./test_project/project_config.json -vv --distclean

  use-package:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-buildnis
          restore-keys: |
            ${{ runner.os }}-pip-buildnis

      - name: Install buildnis package
        run: python -m pip install --upgrade buildnis

      - name: Check if Working
        run: |
          python -m buildnis --version
