name: Windows 2019

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: windows-2019

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: windows-2019-pip-pipenv
          restore-keys: |
            windows-2019-pip-pipenv

      - name: Cache pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: windows-2019-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            windows-2019-pipenv-

      # - name: Install Doxygen
      #   run: |
      #     sudo apt install doxygen

      - name: Setup pipenv
        run: python -m pip install --upgrade pipenv

      - name: Install dependencies using pipenv
        run: |
           cd $GITHUB_WORKSPACE && python -m pipenv install --dev

      - name: Run Buildnis
        run: |
          pipenv run python -m buildnis ./test_project/project_config.json -vv

      - name: Clean Buildnis
        run: |
          cd $GITHUB_WORKSPACE && pipenv run python -m buildnis ./test_project/project_config.json -vv --clean

      # - name: Re-Run Buildnis
      #   run: |
      #     cd $GITHUB_WORKSPACE && pipenv run python -m buildnis ./test_project/project_config.json -vv

  use-package:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: windows-2019-pip-buildnis
          restore-keys: |
            windows-2019-pip-buildnis

      - name: Install buildnis package
        run: python -m pip install --upgrade buildnis

      - name: Check if Works
        run: |
          python -m buildnis --version
