name: Windows 2019

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-src:
    runs-on: windows-2019

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/setup-java@v1
        with:
          java-version: "13" # The JDK version to make available on the path.
          java-package: jdk

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: windows-2019-pip-pipenv
          restore-keys: |
            windows-2019-pip-pipenv

      - name: Cache pipenv
        uses: actions/cache@v2
        with:
          path: ~/.virtualenvs
          key: windows-2019-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            windows-2019-pipenv-

      # takes quite some time, is there a chance to cache something? - Problem is the
      # registry and stuff ...
      - name: Install Doxygen
        run: |
          choco install doxygen.install

      # install sphinx using pip on Windows, somehow the pipenv environment doesn't
      # propagate to the command interpreter called from buildnis.
      - name: Setup pipenv
        run: python -m pip install --upgrade pipenv sphinx

      - name: Install dependencies using pipenv
        run: python -m pipenv install --dev

      - name: Check if Working
        shell: cmd
        run: |
          call pipenv shell
          python -m buildnis --version

      - name: Run Buildnis
        shell: cmd
        run: |
          call pipenv shell
          python -m buildnis ./test_project/project_config.json -v --log-file log_file.txt --gen conf_out

      - uses: actions/upload-artifact@v2
        with:
          name: Windows Buildnis Debug Log
          path: log_file.txt

      - uses: actions/upload-artifact@v2
        with:
          name: Windows Buildnis JSON Configs
          path: test_project/conf_out/*.json

      - name: Clean Buildnis
        shell: cmd
        run: |
          call pipenv shell
          python -m buildnis ./test_project/project_config.json -vv --clean

      - name: Re-Run Buildnis
        shell: cmd
        run: |
          call pipenv shell
          python -m buildnis ./test_project/project_config.json -v --log-file log_file.txt --gen conf_out

      - uses: actions/upload-artifact@v2
        with:
          name: Windows Buildnis Debug Log 2
          path: log_file.txt

      - uses: actions/upload-artifact@v2
        with:
          name: Windows Buildnis JSON Configs 2
          path: test_project/conf_out/*.json

      - name: Dist-Clean Buildnis
        shell: cmd
        run: |
          call pipenv shell
          python -m buildnis ./test_project/project_config.json -vv --distclean

  use-package:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: windows-2019-pip-buildnis
          restore-keys: |
            windows-2019-pip-buildnis

      - name: Install buildnis package
        run: python -m pip install --upgrade buildnis

      - name: Install Sphinx
        run: python -m pip install --upgrade sphinx

      # takes quite some time, is there a chance to cache something? - Problem is the
      # registry and stuff ...
      - name: Install Doxygen
        run: |
          choco install doxygen.install

      - name: Delete Source
        shell: cmd
        run: |
          rmdir /S /Q buildnis

      - name: Check if Pkg Working
        run: |
          python -m buildnis --version

      - name: Run Buildnis Pkg
        shell: cmd
        run: |
          python -m buildnis ./test_project/project_config.json -v --log-file log_file.txt --gen conf_out

      - uses: actions/upload-artifact@v2
        with:
          name: Windows Buildnis Pkg Debug Log
          path: log_file.txt

      - uses: actions/upload-artifact@v2
        with:
          name: Windows Buildnis Pkg JSON Configs
          path: test_project/conf_out/*.json

      - name: Clean Buildnis Pkg
        shell: cmd
        run: |
          python -m buildnis ./test_project/project_config.json -vv --clean

      - name: Re-Run Buildnis Pkg
        shell: cmd
        run: |
          python -m buildnis ./test_project/project_config.json -v --log-file log_file.txt --gen conf_out

      - uses: actions/upload-artifact@v2
        with:
          name: Windows Buildnis Pkg Debug Log 2
          path: log_file.txt

      - uses: actions/upload-artifact@v2
        with:
          name: Windows Buildnis Pkg JSON Configs 2
          path: test_project/conf_out/*.json

      - name: Dist-Clean Buildnis Pkg
        shell: cmd
        run: |
          python -m buildnis ./test_project/project_config.json -vv --distclean
